Fixes worker issues when using SSL and --insecure
```
ssbench-master run-scenario -V 2.0 --insecure -f scenario2

WARNING:root:calculate_scenario_stats: exception from worker 1:
TypeError('sequence item 3: expected string, bool found',)
INFO:root:Traceback (most recent call last):
  File
"/home/rubiojr/env/default/local/lib/python2.7/site-packages/ssbench/worker.py",
line 214, in handle_job
    handler(job_data)
  File
"/home/rubiojr/env/default/local/lib/python2.7/site-packages/ssbench/worker.py",
line 400, in handle_upload_object
    chunk_size=BLOCK_SIZE, contents=contents)
  File
"/home/rubiojr/env/default/local/lib/python2.7/site-packages/ssbench/worker.py",
line 270, in ignoring_http_responses
    token_key = self._token_key(call_info['auth_kwargs'])
  File
"/home/rubiojr/env/default/local/lib/python2.7/site-packages/ssbench/worker.py",
line 249, in _token_key
    return '\x01'.join(parts)
TypeError: sequence item 3: expected string, bool found
```

I think this happens because the worker is actually trying to join
a list with a bool element:

    ['https://identity.bleh.net/v2.0', '2.0', '', True, 'secret',
'\x01\x01\x01\x01\x01\x01admin@bleh.net', '', 'admin@bleh.net']

This patch fixes that hopefully.